name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: pelis
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f Dockerfile -t catujav/testpruebapelis .
    - name: Login Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Push a docker hub 
      run: docker push catujav/testpruebapelis:latest
  
#2
  #deploy:
    #runs-on: ubuntu-latest
    #steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.TOKENDIGITAL}}
    - name: Otro paso
      run:  ssh-keyscan 142.93.63.98 >> ~/.ssh/known_hosts
    - name: Prueba correr dockers
      run: docker stop $(echo $IMAGE_NAME)
        
